apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc

spec:
  replicas: 3
  selector:
    app: myapp
    version: 2.6.1
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
        version: 2.6.1

    spec:
      containers:
        - name: myappcontainer
          image: maha4iac/myonlinebooking:1
          ports:
            - containerPort: 8080

